name: "Continuous Integration for IBF"

on:
    push:
        branches: [master]
        paths-ignore:
            - "./package.json"
            - "./COMMITLOG.md"
    pull_request:
        branches: [master]

jobs:
    detect-changes:
        runs-on: ubuntu-latest

        outputs:
            # ibf-api-service: ${{ steps.filter.outputs.ibf-api-service }}
            # ibf-dashboard: ${{ steps.filter.outputs.ibf-dashboard }}
            # ibf-pipeline: ${{ steps.filter.outputs.ibf-pipeline }}
            cypress-run: ${{ steps.filter.outputs.cypress-run }}

        steps:
            - uses: actions/checkout@v2
            - uses: dorny/paths-filter@v2
              id: filter
              with:
                  filters: |
                      ibf-api-service:
                        - "services/API-service/**"
                      ibf-dashboard:
                        - "interfaces/IBF-dashboard/**"
                      ibf-pipeline:
                        - "services/IBF-pipeline/**"

    # ibf-api-service:
    #     needs: detect-changes
    #     if: ${{ needs.detect-changes.outputs.ibf-api-service == 'true' }}

    #     runs-on: ubuntu-latest

    #     env:
    #         DB_TYPE: ${{ secrets.DB_TYPE }}
    #         DB_HOST: ${{ secrets.DB_HOST }}
    #         DB_PORT: ${{ secrets.DB_PORT }}
    #         DB_DATABASE: ${{ secrets.DB_DATABASE }}
    #         DB_USERNAME: ${{ secrets.DB_USERNAME }}
    #         DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    #         SECRET: ${{ secrets.SECRET }}

    #     strategy:
    #         matrix:
    #             node-version: [12.x]

    #     defaults:
    #         run:
    #             working-directory: "services/API-service"

    #     steps:
    #         - uses: actions/checkout@v2
    #         - name: Use Node.js ${{ matrix.node-version }}
    #           uses: actions/setup-node@v2.1.5
    #           with:
    #               node-version: ${{ matrix.node-version }}
    #         - run: npm ci --no-audit
    #         - run: npm run lint
    #         - run: npm test
    #         - run:
    #               docker build . --file Dockerfile --tag
    #               rodekruis/ibf-api-service:$(date +%s)

    # ibf-dashboard:
    #     needs: detect-changes
    #     if: ${{ needs.detect-changes.outputs.ibf-dashboard == 'true' }}

    #     runs-on: ubuntu-latest

    #     strategy:
    #         matrix:
    #             node-version: [14.x]

    #     defaults:
    #         run:
    #             working-directory: "interfaces/IBF-dashboard"

    #     steps:
    #         - uses: actions/checkout@v2
    #         - name: Use Node.js ${{ matrix.node-version }}
    #           uses: actions/setup-node@v2.1.5
    #           with:
    #               node-version: ${{ matrix.node-version }}
    #         - run: npm ci --no-audit
    #         - run: npm test
    #         - run:
    #               docker build . --file Dockerfile --tag
    #               rodekruis/ibf-dashboard:$(date +%s)

    # ibf-pipeline:
    #     needs: detect-changes
    #     if: ${{ needs.detect-changes.outputs.ibf-pipeline == 'true' }}

    #     runs-on: ubuntu-latest

    #     defaults:
    #         run:
    #             working-directory: "services/IBF-pipeline"

    #     steps:
    #         - uses: actions/checkout@v2
    #         - run:
    #               docker build . --file Dockerfile --tag
    #               rodekruis/ibf-pipeline:$(date +%s)

    cypress-run:
        needs: detect-changes
        if: |
            ${{ needs.detect-changes.outputs.ibf-pipeline == 'true' }} ||
            ${{ needs.detect-changes.outputs.ibf-dashboard == 'true' }} ||
            ${{ needs.detect-changes.outputs.ibf-api-service == 'true' }}

        runs-on: ubuntu-latest

        env:
            DB_TYPE: ${{ secrets.DB_TYPE }}
            DB_HOST_TEST_VM: ${{ secrets.DB_HOST }}
            DB_PORT: ${{ secrets.DB_PORT }}
            DB_DATABASE_TEST_VM: ${{ secrets.DB_DATABASE }}
            DB_USERNAME_TEST_VM: ${{ secrets.DB_USERNAME }}
            DB_PASSWORD_TEST_VM: ${{ secrets.DB_PASSWORD}}
            SECRET: ${{ secrets.SECRET }}
            DB_HOST: ibf-local-db
            DB_DATABASE: ibf
            DB_USERNAME: ibf
            DB_PASSWORD: ibf
            DB_PORT_LOCAL: 5437

        # defaults:
        #     run:
        #         working-directory: "interfaces/tests"
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            # Install NPM dependencies, cache them correctly
            # and run all Cypress tests
            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  command: chmod +x prepare-test.sh && ./prepare-test.sh
                  start: npm run start:cypress"
    # bump-version:
    #     needs: [ibf-api-service, ibf-dashboard, ibf-pipeline]
    #     if: |
    #         always() &&
    #         github.event_name == 'push'
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Wait for previous workflow to complete
    #           uses: softprops/turnstyle@v1
    #           with:
    #               abort-after-seconds: 1800
    #           env:
    #               GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
    #         - uses: actions/checkout@v2
    #         - name: Bump version and push tag
    #           uses: TriPSs/conventional-changelog-action@v3
    #           with:
    #               github-token: ${{ secrets.ACTIONS_TOKEN }}
    #               git-message: "chore(release): {version}"
    #               release-count: 10
